name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger workflow on tags matching v*, e.g. v1.0.0
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create ZIP file
        run: |
          zip -r AkunSwitcher.zip . -x "*.git*" -x ".github/*" -x "assets/images/icon.svg" -x "*.md"

      - name: Build CRX file
        run: |
          mkdir temp_build
          unzip AkunSwitcher.zip -d temp_build
          npx -y crx3 -p AkunSwitcher.pem -o AkunSwitcher.crx temp_build/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            AkunSwitcher.zip
            AkunSwitcher.crx
          generate_release_notes: true
